/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "GSSAPI"
 * 	found in "../gssapi.asn1"
 */

#include "InitialContextToken.h"

static asn_TYPE_member_t asn_MBR_InitialContextToken_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct InitialContextToken, thisMech),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_MechType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"thisMech"
		},
	{ ATF_ANY_TYPE | ATF_NOFLAGS, 0, offsetof(struct InitialContextToken, innerContextToken),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"innerContextToken"
		},
};
static const ber_tlv_tag_t asn_DEF_InitialContextToken_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_InitialContextToken_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 } /* thisMech */
};
static asn_SEQUENCE_specifics_t asn_SPC_InitialContextToken_specs_1 = {
	sizeof(struct InitialContextToken),
	offsetof(struct InitialContextToken, _asn_ctx),
	asn_MAP_InitialContextToken_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_InitialContextToken = {
	"InitialContextToken",
	"InitialContextToken",
	&asn_OP_SEQUENCE,
	asn_DEF_InitialContextToken_tags_1,
	sizeof(asn_DEF_InitialContextToken_tags_1)
		/sizeof(asn_DEF_InitialContextToken_tags_1[0]) - 1, /* 1 */
	asn_DEF_InitialContextToken_tags_1,	/* Same as above */
	sizeof(asn_DEF_InitialContextToken_tags_1)
		/sizeof(asn_DEF_InitialContextToken_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_InitialContextToken_1,
	2,	/* Elements count */
	&asn_SPC_InitialContextToken_specs_1	/* Additional specs */
};

