/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "GSSAPI"
 * 	found in "../gssapi.asn1"
 */

#ifndef	_MechTypeList_H_
#define	_MechTypeList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MechType.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MechTypeList */
typedef struct MechTypeList {
	A_SEQUENCE_OF(MechType_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MechTypeList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MechTypeList;
extern asn_SET_OF_specifics_t asn_SPC_MechTypeList_specs_1;
extern asn_TYPE_member_t asn_MBR_MechTypeList_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _MechTypeList_H_ */
#include <asn_internal.h>
