/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "GSSAPI"
 * 	found in "../gssapi.asn1"
 */

#ifndef	_NegTokenInit_H_
#define	_NegTokenInit_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MechTypeList.h"
#include "ContextFlags.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NegTokenInit */
typedef struct NegTokenInit {
	MechTypeList_t	 mechTypes;
	ContextFlags_t	*reqFlags	/* OPTIONAL */;
	OCTET_STRING_t	*mechToken	/* OPTIONAL */;
	OCTET_STRING_t	*mechListMIC	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NegTokenInit_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NegTokenInit;
extern asn_SEQUENCE_specifics_t asn_SPC_NegTokenInit_specs_1;
extern asn_TYPE_member_t asn_MBR_NegTokenInit_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NegTokenInit_H_ */
#include <asn_internal.h>
