/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "GSSAPI"
 * 	found in "../gssapi.asn1"
 */

#include "NegTokenResp.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_negState_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_negState_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_negState_value2enum_2[] = {
	{ 0,	16,	"accept-completed" },
	{ 1,	17,	"accept-incomplete" },
	{ 2,	6,	"reject" },
	{ 3,	11,	"request-mic" }
};
static const unsigned int asn_MAP_negState_enum2value_2[] = {
	0,	/* accept-completed(0) */
	1,	/* accept-incomplete(1) */
	2,	/* reject(2) */
	3	/* request-mic(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_negState_specs_2 = {
	asn_MAP_negState_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_negState_enum2value_2,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_negState_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_negState_2 = {
	"negState",
	"negState",
	&asn_OP_NativeEnumerated,
	asn_DEF_negState_tags_2,
	sizeof(asn_DEF_negState_tags_2)
		/sizeof(asn_DEF_negState_tags_2[0]), /* 2 */
	asn_DEF_negState_tags_2,	/* Same as above */
	sizeof(asn_DEF_negState_tags_2)
		/sizeof(asn_DEF_negState_tags_2[0]), /* 2 */
	{ &asn_OER_type_negState_constr_2, &asn_PER_type_negState_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_negState_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_NegTokenResp_1[] = {
	{ ATF_POINTER, 4, offsetof(struct NegTokenResp, negState),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_negState_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"negState"
		},
	{ ATF_POINTER, 3, offsetof(struct NegTokenResp, supportedMech),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MechType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedMech"
		},
	{ ATF_POINTER, 2, offsetof(struct NegTokenResp, responseToken),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"responseToken"
		},
	{ ATF_POINTER, 1, offsetof(struct NegTokenResp, mechListMIC),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mechListMIC"
		},
};
static const int asn_MAP_NegTokenResp_oms_1[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_NegTokenResp_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NegTokenResp_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* negState */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* supportedMech */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* responseToken */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* mechListMIC */
};
asn_SEQUENCE_specifics_t asn_SPC_NegTokenResp_specs_1 = {
	sizeof(struct NegTokenResp),
	offsetof(struct NegTokenResp, _asn_ctx),
	asn_MAP_NegTokenResp_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_NegTokenResp_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NegTokenResp = {
	"NegTokenResp",
	"NegTokenResp",
	&asn_OP_SEQUENCE,
	asn_DEF_NegTokenResp_tags_1,
	sizeof(asn_DEF_NegTokenResp_tags_1)
		/sizeof(asn_DEF_NegTokenResp_tags_1[0]), /* 1 */
	asn_DEF_NegTokenResp_tags_1,	/* Same as above */
	sizeof(asn_DEF_NegTokenResp_tags_1)
		/sizeof(asn_DEF_NegTokenResp_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NegTokenResp_1,
	4,	/* Elements count */
	&asn_SPC_NegTokenResp_specs_1	/* Additional specs */
};

