/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "GSSAPI"
 * 	found in "../gssapi.asn1"
 */

#include "NegTokenInit.h"

asn_TYPE_member_t asn_MBR_NegTokenInit_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NegTokenInit, mechTypes),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MechTypeList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mechTypes"
		},
	{ ATF_POINTER, 3, offsetof(struct NegTokenInit, reqFlags),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ContextFlags,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reqFlags"
		},
	{ ATF_POINTER, 2, offsetof(struct NegTokenInit, mechToken),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mechToken"
		},
	{ ATF_POINTER, 1, offsetof(struct NegTokenInit, mechListMIC),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mechListMIC"
		},
};
static const int asn_MAP_NegTokenInit_oms_1[] = { 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_NegTokenInit_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NegTokenInit_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mechTypes */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* reqFlags */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* mechToken */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* mechListMIC */
};
asn_SEQUENCE_specifics_t asn_SPC_NegTokenInit_specs_1 = {
	sizeof(struct NegTokenInit),
	offsetof(struct NegTokenInit, _asn_ctx),
	asn_MAP_NegTokenInit_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_NegTokenInit_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NegTokenInit = {
	"NegTokenInit",
	"NegTokenInit",
	&asn_OP_SEQUENCE,
	asn_DEF_NegTokenInit_tags_1,
	sizeof(asn_DEF_NegTokenInit_tags_1)
		/sizeof(asn_DEF_NegTokenInit_tags_1[0]), /* 1 */
	asn_DEF_NegTokenInit_tags_1,	/* Same as above */
	sizeof(asn_DEF_NegTokenInit_tags_1)
		/sizeof(asn_DEF_NegTokenInit_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NegTokenInit_1,
	4,	/* Elements count */
	&asn_SPC_NegTokenInit_specs_1	/* Additional specs */
};

